### ISSUE TITLE
Possible Bug Parsing DVPT2 + RedDim

### ISSUE THREAD

**Issue by ledragna** [jbloino/estampes#3]
Parsing log file of an anharmonic calculation in which the RedDim keyword was used produces:
``` File "/home/user/pyenvs/estampes/bin/esballast", line 33, in <module>
    sys.exit(load_entry_point('estampes', 'console_scripts', 'esballast')())
  File "/home/user/git/estampes/progs/ballast.py", line 499, in main
    figdata, spcdata, curves = parse_inifile(args.optfile)
  File "/home/user/git/estampes/progs/ballast.py", line 402, in parse_inifile
    curves[key]['data'] = Spectrum(optsec['file'], spc, lvl, yid)
  File "/home/user/git/estampes/estampes/base/spectrum.py", line 291, in __init__
    self.load_data(ylabel)
  File "/home/user/git/estampes/estampes/base/spectrum.py", line 437, in load_data
    isinstance(ydata[mode], float)):
KeyError: 301
```
The same error occurs calling directly the parser within a dedicated script (outside ballast).
Energy seems to be parsed properly, the issue rises with the properties both `build_qlabel('dipstr', level='A')` and `build_qlabel('rotstr', level='A')`.

The issue is not observed in GVPT2 calculations.

**Comment by jbloino** [comment]
Should be fixed in commit https://github.com/jbloino/estampes/commit/e7811a24a45163b047a4a86f9030959b7244dc60 and included in **v0.4.2**.
There are current limitations:
It may makes sense to extract all energies or only those relevant for the spectra. In the latter case, it is expected that users would want transition data, so requesting `vtrans` together. Hence, `parser.gaussian.glog` will clean non-active states **only** if the user requests together `vlevel` and `vtrans`.  There is currently no workaround to do it outside `glog` since it is specific to the Gaussian output file.
Error messages provided by _Ballast_ have also been improved, to avoid tracebacks dumps and give less cryptic messages (commit: https://github.com/jbloino/estampes/commit/60bb36786d606c98d1f77e7b340086b6783cde06)

**Comment by ledragna** [comment]
I'm still experiencing some issue.
In attempting to reading data from a reddim calculation with `pt2model=idvpt2`, even if both `vlevel` and `vtrans` are included, I get:
```
File ~/git/estampes/estampes/parser/gaussian/glog.py:2549, in get_data(dfobj, error_noqty, *qlabels, **keys4qlab)
   2548 try:
-> 2549     data = parse_data(qty_dict, key2blocks, qlab2key, ndata, datablocks,
   2550                       gver, error_noqty)
   2551 except (QuantityError, NotImplementedError):

File ~/git/estampes/estampes/parser/gaussian/glog.py:2459, in parse_data(qdict, key2blocks, qlab2key, ndatablock, datablocks, gver, raise_error)
   2458     if 'vtrans' in args and 'vlevel' in args:
-> 2459         __del_nonactive_modes(data[args['vtrans']], data[args['vlevel']])
   2460 return data

File ~/git/estampes/estampes/parser/gaussian/glog.py:2819, in __del_nonactive_modes(vtrans, vlevel)
   2818 remove = False
-> 2819 if len(to) > 1 or to[0][1] != 1:
   2820     for mode, _ in to:

IndexError: string index out of range
```
